# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Subjects', '0001_initial'),
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RollNo', models.CharField(max_length=50, unique=True)),
                ('Name', models.CharField(blank=True, max_length=200)),
                ('DateOfBirth', models.DateField(blank=True, null=True)),
                ('Course', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Courses.Course')),
                ('Subjects', models.ManyToManyField(blank=True, null=True, to='Subjects.Subject')),
            ],
        ),
    ]
