# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Subjects',
            field=models.ManyToManyField(blank=True, to='Subjects.Subject'),
        ),
    ]
