# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='IssueId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Students.Student'),
        ),
        migrations.AlterField(
            model_name='sports',
            name='IssueID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Students.Student'),
        ),
    ]
