# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facilities', '0002_auto_20170226_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'Library'},
        ),
        migrations.AlterModelOptions(
            name='sports',
            options={'verbose_name_plural': 'Sports'},
        ),
    ]
