# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facilities', '0003_auto_20170226_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'Library : Books Issued'},
        ),
        migrations.AlterModelOptions(
            name='sports',
            options={'verbose_name_plural': 'Sports : Items Issued'},
        ),
    ]
