# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(blank=True, choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('Ph.D', 'Ph.D')], max_length=100, null=True)),
                ('BranchName', models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Electrical', 'Electrical'), ('Electronics and Communications', 'Electronics and Communications'), ('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('Biotech', 'Biotech'), ('None', 'None')], default='None', max_length=100, null=True)),
                ('HOD', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
